import React from "react";
import styles from "../../css/app.module.css";

export function GenreButton({
    defaultClass,
    selectedClass,
    label,
    value,
    isSelected,
    onClick,
}) {
    return (
        <button
            className={`${isSelected ? selectedClass : defaultClass} ${
                styles.buttonStyle
            }`}
            onClick={() => onClick(value)}
        >
            <span>{label}</span>
            <img
                src={isSelected ? "/done.svg" : "/plus1.svg"}
                width={20}
                height={20}
                alt="Icon"
                className="plusIcon"
            />
        </button>
    );
}

export function GenreList({ onGenreSelect, selectedGenres }) {
    return (
        <div className={styles.moodListWrapper}>
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("pop")}
                defaultClass={styles.moodListYellow}
                selectedClass={styles.selectedMoodListYellow}
                label="pop"
                value="pop"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("rock")}
                defaultClass={styles.moodListOrange}
                selectedClass={styles.selectedMoodListOrange}
                label="rock"
                value="rock"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("jazz")}
                defaultClass={styles.moodListBlue}
                selectedClass={styles.selectedMoodListBlue}
                label="jazz"
                value="jazz"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("classical")}
                defaultClass={styles.moodListPurple}
                selectedClass={styles.selectedMoodListPurple}
                label="classical"
                value="classical"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("romance")}
                defaultClass={styles.moodListPink}
                selectedClass={styles.selectedMoodListPink}
                label="romance"
                value="romance"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("world-music")}
                defaultClass={styles.moodListGreen}
                selectedClass={styles.selectedMoodListGreen}
                label="world-music"
                value="world-music"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("movies")}
                defaultClass={styles.moodListOrange}
                selectedClass={styles.selectedMoodListOrange}
                label="movies"
                value="movies"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("country")}
                defaultClass={styles.moodListYellow}
                selectedClass={styles.selectedMoodListYellow}
                label="country"
                value="country"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("dance")}
                defaultClass={styles.moodListYellow}
                selectedClass={styles.selectedMoodListYellow}
                label="dance"
                value="dance"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("punk")}
                defaultClass={styles.moodListOrange}
                selectedClass={styles.selectedMoodListOrange}
                label="punk"
                value="punk"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("summer")}
                defaultClass={styles.moodListGreen}
                selectedClass={styles.selectedMoodListGreen}
                label="summer"
                value="summer"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("sleep")}
                defaultClass={styles.moodListPurple}
                selectedClass={styles.selectedMoodListPurple}
                label="sleep"
                value="sleep"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("j-pop")}
                defaultClass={styles.moodListYellow}
                selectedClass={styles.selectedMoodListYellow}
                label="j-pop"
                value="j-pop"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("k-pop")}
                defaultClass={styles.moodListPurple}
                selectedClass={styles.selectedMoodListPurple}
                label="k-pop"
                value="k-pop"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("study")}
                defaultClass={styles.moodListPink}
                selectedClass={styles.selectedMoodListPink}
                label="study"
                value="study"
            />
            <GenreButton
                onClick={onGenreSelect}
                isSelected={selectedGenres.includes("全ジャンル")}
                defaultClass={styles.moodListPurple}
                selectedClass={styles.selectedMoodListPurple}
                label="おまかせ"
                value="全ジャンル"
            />
        </div>
    );
}

